### ISSUE TITLE
编辑模式 缺少排序功能

### ISSUE THREAD

**Issue by DevYao** [luckysmg/flutter_swipe_action_cell#35]
希望 编辑模式下可以和iOS原生一样支持拖拽排序

**Comment by luckysmg** [comment]
这个我这里已经确定无法支持，您可以尝试使用reorderListview



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yao ***@***.***&gt;
发送时间: 2021年9月30日 21:25
收件人: luckysmg/flutter_swipe_action_cell ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[luckysmg/flutter_swipe_action_cell] 编辑模式 缺少排序功能 (#35)





 
希望 编辑模式下可以和iOS原生一样支持拖拽排序
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
