### ISSUE TITLE
 Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by Ckefan** [luckysmg/flutter_swipe_action_cell#49]
Try calling using ?. instead.
        WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
                                ^^^^^^^^^^^^^^^^^^^^

**Comment by luckysmg** [comment]
3.0.0 and later is for flutter 3



发自我的iPhone


------------------ Original ------------------
From: jeck.chen ***@***.***&gt;
Date: Sun,Jun 12,2022 5:10 PM
To: luckysmg/flutter_swipe_action_cell ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [luckysmg/flutter_swipe_action_cell]  Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null. (Issue #49)





 
Try calling using ?. instead.
 WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
 ^^^^^^^^^^^^^^^^^^^^

**Comment by Ckefan** [comment]
thank you very much
